// <auto-generated />
namespace Eron.core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class confinit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(confinit));
        
        string IMigrationMetadata.Id
        {
            get { return "201607111603069_conf-init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
