// <auto-generated />
namespace Eron.core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class confslideendtimechange1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(confslideendtimechange1));
        
        string IMigrationMetadata.Id
        {
            get { return "201610061640402_conf-slide-endtime-change-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
