// <auto-generated />
namespace Eron.core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class confaddinsight : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(confaddinsight));
        
        string IMigrationMetadata.Id
        {
            get { return "201608040851329_conf-add-insight"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
