// <auto-generated />
namespace Eron.DataAccess.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class confaddblog2018083101 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(confaddblog2018083101));
        
        string IMigrationMetadata.Id
        {
            get { return "201808302141556_conf-add-blog-2018-08-31-01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
