// <auto-generated />
namespace Eron.DataAccess.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class conftransactionbanknametype20180614 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(conftransactionbanknametype20180614));
        
        string IMigrationMetadata.Id
        {
            get { return "201806141153238_conf-transaction-bank-name-type-2018-06-14"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
