// <auto-generated />
namespace Eron.DataAccess.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class confaddblogcategory2018091001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(confaddblogcategory2018091001));
        
        string IMigrationMetadata.Id
        {
            get { return "201809101800041_conf-add-blog-category-2018-09-10-01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
