//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eron.core.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eron.core.App_GlobalResources.GlobalResources", typeof(GlobalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همه مجموعه ها.
        /// </summary>
        public static string AllCategories {
            get {
                return ResourceManager.GetString("AllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همه مطالب.
        /// </summary>
        public static string AllContent {
            get {
                return ResourceManager.GetString("AllContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همه زبان ها.
        /// </summary>
        public static string AllLanguages {
            get {
                return ResourceManager.GetString("AllLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همه منو ها.
        /// </summary>
        public static string AllMenus {
            get {
                return ResourceManager.GetString("AllMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمامی صفحات.
        /// </summary>
        public static string AllPages {
            get {
                return ResourceManager.GetString("AllPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همه فروشگاه ها.
        /// </summary>
        public static string AllShops {
            get {
                return ResourceManager.GetString("AllShops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نویسنده.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش زمینه.
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگشت به لیست.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تماس کاری.
        /// </summary>
        public static string BusinessTel {
            get {
                return ResourceManager.GetString("BusinessTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعه.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعه ای را انتخاب کنید.
        /// </summary>
        public static string ChooseCategory {
            get {
                return ResourceManager.GetString("ChooseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زبان را انتخاب کنید.
        /// </summary>
        public static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار رمز عبور.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطلب.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن.
        /// </summary>
        public static string ContentData {
            get {
                return ResourceManager.GetString("ContentData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت محتوا.
        /// </summary>
        public static string ContentManagement {
            get {
                return ResourceManager.GetString("ContentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت.
        /// </summary>
        public static string ContentState {
            get {
                return ResourceManager.GetString("ContentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت مجموعه.
        /// </summary>
        public static string CreateCategory {
            get {
                return ResourceManager.GetString("CreateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت مطلب جدید.
        /// </summary>
        public static string CreateContent {
            get {
                return ResourceManager.GetString("CreateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت زبان جدید.
        /// </summary>
        public static string CreateLanguage {
            get {
                return ResourceManager.GetString("CreateLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت منو.
        /// </summary>
        public static string CreateMenu {
            get {
                return ResourceManager.GetString("CreateMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت صفحه.
        /// </summary>
        public static string CreatePage {
            get {
                return ResourceManager.GetString("CreatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت فروشگاه.
        /// </summary>
        public static string CreateShop {
            get {
                return ResourceManager.GetString("CreateShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ثبت.
        /// </summary>
        public static string CreateTime {
            get {
                return ResourceManager.GetString("CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه کنونی.
        /// </summary>
        public static string CurrentPage {
            get {
                return ResourceManager.GetString("CurrentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزئیات معمولی.
        /// </summary>
        public static string DefaultDetails {
            get {
                return ResourceManager.GetString("DefaultDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف مجموعه.
        /// </summary>
        public static string DeleteCategory {
            get {
                return ResourceManager.GetString("DeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از حذف این مورد اطمینان دارید؟.
        /// </summary>
        public static string DeleteConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف مطلب.
        /// </summary>
        public static string DeleteContent {
            get {
                return ResourceManager.GetString("DeleteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف زبان.
        /// </summary>
        public static string DeleteLanguage {
            get {
                return ResourceManager.GetString("DeleteLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف منو.
        /// </summary>
        public static string DeleteMenu {
            get {
                return ResourceManager.GetString("DeleteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف صفحه.
        /// </summary>
        public static string DeletePage {
            get {
                return ResourceManager.GetString("DeletePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات ورودی قبلا در پایگاه ثبت شده. امکان ثبت تکراری وجود ندارد.
        /// </summary>
        public static string DuplicationErrorMessage {
            get {
                return ResourceManager.GetString("DuplicationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش مجموعه.
        /// </summary>
        public static string EditCategory {
            get {
                return ResourceManager.GetString("EditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش مطلب.
        /// </summary>
        public static string EditContent {
            get {
                return ResourceManager.GetString("EditContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش زبان.
        /// </summary>
        public static string EditLanguage {
            get {
                return ResourceManager.GetString("EditLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش منو.
        /// </summary>
        public static string Editmenu {
            get {
                return ResourceManager.GetString("Editmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایشگر.
        /// </summary>
        public static string Editor {
            get {
                return ResourceManager.GetString("Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش صفحه.
        /// </summary>
        public static string EditPage {
            get {
                return ResourceManager.GetString("EditPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام انگلیسی.
        /// </summary>
        public static string EnglishName {
            get {
                return ResourceManager.GetString("EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد کاربر جدید با مشکل مواجه شد..
        /// </summary>
        public static string ErrorRegisteringUser {
            get {
                return ResourceManager.GetString("ErrorRegisteringUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک خارجی.
        /// </summary>
        public static string ExternalLink {
            get {
                return ResourceManager.GetString("ExternalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرچم.
        /// </summary>
        public static string Flag {
            get {
                return ResourceManager.GetString("Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمعه.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گالری.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس محل سکونت.
        /// </summary>
        public static string HomeAddress {
            get {
                return ResourceManager.GetString("HomeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعت.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک داخلی.
        /// </summary>
        public static string InternalLink {
            get {
                return ResourceManager.GetString("InternalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهانی ( فارق از زبان خاص ).
        /// </summary>
        public static string IsGlobal {
            get {
                return ResourceManager.GetString("IsGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمات کلیدی.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زبان.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد زبان.
        /// </summary>
        public static string LanguageCode {
            get {
                return ResourceManager.GetString("LanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات زبان.
        /// </summary>
        public static string LanguageSetting {
            get {
                return ResourceManager.GetString("LanguageSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول جغرافیایی.
        /// </summary>
        public static string Lat {
            get {
                return ResourceManager.GetString("Lat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض جغرافیایی.
        /// </summary>
        public static string Lng {
            get {
                return ResourceManager.GetString("Lng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام محلی.
        /// </summary>
        public static string LocalName {
            get {
                return ResourceManager.GetString("LocalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منو ها.
        /// </summary>
        public static string Menus {
            get {
                return ResourceManager.GetString("Menus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات منو.
        /// </summary>
        public static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحوه باز شدن لینک.
        /// </summary>
        public static string MenuTarget {
            get {
                return ResourceManager.GetString("MenuTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع منو.
        /// </summary>
        public static string MenuType {
            get {
                return ResourceManager.GetString("MenuType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دقیقه.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ویرایش.
        /// </summary>
        public static string ModifiedTime {
            get {
                return ResourceManager.GetString("ModifiedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوشنبه.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه جدید.
        /// </summary>
        public static string NewPage {
            get {
                return ResourceManager.GetString("NewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسویه نشده.
        /// </summary>
        public static string NotCheckedOut {
            get {
                return ResourceManager.GetString("NotCheckedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یافت نشد.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صاحب امتیاز.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت صفحات.
        /// </summary>
        public static string PageManagement {
            get {
                return ResourceManager.GetString("PageManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحات.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منو پدر.
        /// </summary>
        public static string ParentMenu {
            get {
                return ResourceManager.GetString("ParentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پسورد.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده صحیح نمی باشد. لطفا پسورد خود را تایید کنید..
        /// </summary>
        public static string PasswordConfirmationError {
            get {
                return ResourceManager.GetString("PasswordConfirmationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد {0} باید حداقل {2} کاراکتر باشد..
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پستی.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;اطلاعات وارد شده برای فیلد {1} معتبر نمی باشد. &quot;.
        /// </summary>
        public static string PropertyValueInvalid {
            get {
                return ResourceManager.GetString("PropertyValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتشار.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتشار یافته.
        /// </summary>
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتمام زمان انتشار.
        /// </summary>
        public static string PublishEndTime {
            get {
                return ResourceManager.GetString("PublishEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آغاز زمان انتشار.
        /// </summary>
        public static string PublishStartTime {
            get {
                return ResourceManager.GetString("PublishStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ انتشار.
        /// </summary>
        public static string PublishTime {
            get {
                return ResourceManager.GetString("PublishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا فیلد {0} را پر کنید.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شنبه.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات فروشگاه.
        /// </summary>
        public static string ShopDetails {
            get {
                return ResourceManager.GetString("ShopDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام فروشگاه.
        /// </summary>
        public static string ShopName {
            get {
                return ResourceManager.GetString("ShopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش نام نویسنده.
        /// </summary>
        public static string ShowAuthor {
            get {
                return ResourceManager.GetString("ShowAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش تاریخ و ساعت.
        /// </summary>
        public static string ShowDateTime {
            get {
                return ResourceManager.GetString("ShowDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن آدرس.
        /// </summary>
        public static string Slug {
            get {
                return ResourceManager.GetString("Slug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی.
        /// </summary>
        public static string SocialNumber {
            get {
                return ResourceManager.GetString("SocialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ شروع.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیر منو.
        /// </summary>
        public static string SubMenu {
            get {
                return ResourceManager.GetString("SubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهرستان.
        /// </summary>
        public static string SubState {
            get {
                return ResourceManager.GetString("SubState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خلاصه.
        /// </summary>
        public static string Summery {
            get {
                return ResourceManager.GetString("Summery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یکشنبه.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیرفعال.
        /// </summary>
        public static string Suspend {
            get {
                return ResourceManager.GetString("Suspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فروشگاه های معلق.
        /// </summary>
        public static string SuspendedShops {
            get {
                return ResourceManager.GetString("SuspendedShops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تگ.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تماس.
        /// </summary>
        public static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنج شنبه.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سه شنبه.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتشر نشده.
        /// </summary>
        public static string Unpublished {
            get {
                return ResourceManager.GetString("Unpublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ بروز رسانی.
        /// </summary>
        public static string UpdateTime {
            get {
                return ResourceManager.GetString("UpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس صفحه.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چهارشنبه.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس محل کار.
        /// </summary>
        public static string WorkAddress {
            get {
                return ResourceManager.GetString("WorkAddress", resourceCulture);
            }
        }
    }
}
